[package]
name = "captcha_dataset_marker"
version = "0.0.1"
edition = "2021"

[dependencies]
yapt = { git = "https://github.com/worksoup/yapt.git" }
image = "0.25"
slint = "1.8"

[build-dependencies]
slint-build = "1.8.0"
